#!/usr/bin/env python

import argparse
import logging

import gpxlib

DEFAULT_LIMIT = 10


def main():
    # https://stackoverflow.com/questions/10027242/python-argparse-to-handle-arbitrary-numeric-options-like-head1
    parser = argparse.ArgumentParser(description="The head equivalent for GPX files")
    parser.add_argument("-0", action="store_true", help="null separator")
    parser.add_argument("-o", "--output", help="Write output to OUTPUT")
    parser.add_argument("file", nargs="?")
    args, pass_args = parser.parse_known_args()

    logging.basicConfig(level=1, format="%(asctime)s -- %(message)s")

    gpx_in, points = gpxlib.read(args.file)
    gpx_out, segment = gpxlib.create(gpx_in)

    limit = abs(int(pass_args[0])) if len(pass_args) else DEFAULT_LIMIT
    for idx in range(0, limit):
        segment.points.append(points[idx])

    s = gpx_out.to_xml()
    if args.output:
        with open(args.output, "w") as f:
            f.write(s)
    else:
        print(s)


if __name__ == "__main__":
    main()
