#!/usr/bin/env python

import sys
import argparse
import logging
import traceback

import gpxlib


def main():
    parser = argparse.ArgumentParser(description="A tool to shift timestamps in a GPX file")
    parser.add_argument("-v", "--verbose", help="Increase output verbosity (thus rendering output XML unusable)", action="store_true")
    parser.add_argument("-l", "--last", help="Relative shift", action="store_true")
    parser.add_argument("-o", "--output", help="Write output to OUTPUT")
    parser.add_argument('value')
    parser.add_argument('file', nargs='?')
    args, pass_args = parser.parse_known_args()
    args = parser.parse_args()

    logging.basicConfig(level=1, format="%(asctime)s -- %(message)s")

    gpx_in, points = gpxlib.read(args.file)
    gpx_out, segment = gpxlib.create(gpx_in)

    try:
        segment.points = gpxlib.gpxshift(points, args.value, args.last)
    except Exception as e:
        sys.exit(traceback.format_exc())

    s = gpx_out.to_xml()
    if args.output:
        with open(args.output, 'w') as f:
            f.write(s)
    else:
        print(s)


if __name__ == '__main__':
    main()
