#!/usr/bin/env python

import argparse
import logging
import sys
import traceback

import gpxlib


def main():
    # https://stackoverflow.com/questions/10027242/python-argparse-to-handle-arbitrary-numeric-options-like-head1
    parser = argparse.ArgumentParser(description="Outputs GPX points in reverse order")
    parser.add_argument("file", nargs="?")
    parser.add_argument(
        "-t",
        "--time",
        help="Don't invert timestamps, only GPS points",
        action="store_true",
    )
    parser.add_argument("-o", "--output", help="Write output to OUTPUT")
    args, pass_args = parser.parse_known_args()

    logging.basicConfig(level=1, format="%(asctime)s -- %(message)s")

    # read input, create GPX output
    gpx_in, points = gpxlib.read(args.file)
    gpx_out, segment = gpxlib.create(gpx_in)

    try:
        segment.points = gpxlib.gpxtac(points, args.time)
    except Exception:
        sys.exit(traceback.format_exc())

    s = gpx_out.to_xml()
    if args.output:
        with open(args.output, "w") as f:
            f.write(s)
    else:
        print(s)


if __name__ == "__main__":
    main()
